### ISSUE TITLE
Change MaxCircuit

### ISSUE THREAD

**Issue by MvQuast** [fondberg/easee_hass#120]
Hi,
first of all - thank you for creating this awesome HA integration.
One thing I observed: Is it possible to programmatically change MaxCircuit?

Background: when charging from PV, I'd like to periodically adjust charged Amps according to current power overhead.

Thanks,
Marcel

**Comment by olalid** [comment]
Hi and thank you.
It is best to use dynamic circuit limit for this purpose.

Changing the max circuit limit will write to flash in the device each time, so it is not recommended to do that often because there is a risk the flash will wear out.
But there are in any case services that you can use to set the current limits.
easee.set_circuit_dynamic_limit or easee.set_charger_circuit_dynamic_limit (both do the exact same thing, it just the handle that is different).

**Comment by MvQuast** [comment]
Reason for this idea was that changing this from Easee app directly changed the max circuit limit down.
Use case: when I know that my PV currently has 2 kW left, I would limit this to 10A, to avoid draining my battery.

**Comment by olalid** [comment]
Dynamic circuit works the same way. 
The lowest value of all the limits "wins".
So if your max circuit limit is set to 14A and the dynamic circuit limit is set to 10A, the current will be limited to 10A.

**Comment by olalid** [comment]
Please close the issue if this solved your problem.

**Comment by MvQuast** [comment]
Hi,
I modified the value within Easee App - dynamic circuit limit always stays at 40 A, no matter if I choose 15A or only 10A - so the value that can be dynamically adjusted is max_circuit_limit. (which is not the overall setup of your installation location like fuse parameters).
Another challenge: no matter if we talk about Dynamic Circuit limit or Max circuit limit - it's a sensor within HASS, so it's just readable but not modifyable.

**Comment by olalid** [comment]
As I said above, there are services within the Easee integration in HA which you can use to set the dynamic charging limit.
(And yes, the app supports only setting the max circuit limit, but that is kind of irrelevant).
Which means that to change the dynamic circuit limit you must call one of these services.

Typically you would make an automation that changes the limit when a new limit has been calculated.
Something along these lines:

```
- id: charging_current
  alias: Set dynamic charging current
  trigger:
  - platform: state
    entity_id: sensor.allowed_current
  action:
  - service: easee.set_circuit_dynamic_limit
    data_template:
      circuit_id: 20874
      currentP1: "{{ states.sensor.allowed_current.state }}"
      currentP2: "{{ states.sensor.allowed_current.state }}"
      currentP3: "{{ states.sensor.allowed_current.state }}"
```

**Comment by hollowboarder** [comment]
> As I said above, there are services within the Easee integration in HA which you can use to set the dynamic circuit limit. (And yes, the app supports only setting the max circuit limit, but that is kind of irrelevant). Which means that to change the dynamic circuit limit you must call one of these services.
> 
> Typically you would make an automation that changes the limit when a new limit has been calculated. Something along these lines:
> 
> ```
> - id: charging_current
>   alias: Set dynamic charging current
>   trigger:
>   - platform: state
>     entity_id: sensor.allowed_current
>   action:
>   - service: easee.set_circuit_dynamic_limit
>     data_template:
>       circuit_id: 12345
>       currentP1: "{{ states.sensor.allowed_current.state }}"
>       currentP2: "{{ states.sensor.allowed_current.state }}"
>       currentP3: "{{ states.sensor.allowed_current.state }}"
> ```

Hi!
Im trying to use that Code but it doesnt work with my Charger. The maximum circuit Limit doesnt change at all it always stays at 40A

Maybe the circuit id is wrong? Which id i have to use?
for testing reason i try this
`currentP1: "{{ 10 }}" `
To Set it to 10A on each Phase. The Event is fired but the Charger stays always on 40A

Maybe anyone can help?
Thanks

**Comment by AMajland** [comment]
I've done some testing today - before finding this thread,  So see this a thumbs up and a confirmation that it is working ....

It seems that the Easee App uses "Max circuit limit" - (That can't be set from HA as described above)

"Dyn charger limit" works to reduce current.  But only if it is set after charging has started. Otherwise the charger just said "In que - Load balancing"

The right one to use is "Dyn circuit limit". That can be set before charging has even started and will not prohibit the charger to start when a car is connected or a schedule turns it on

**Comment by hollowboarder** [comment]
> I've done some testing today - before finding this thread, So see this a thumbs up and a confirmation that it is working ....
> 
> It seems that the Easee App uses "Max circuit limit" - (That can't be set from HA as described above)
> 
> "Dyn charger limit" works to reduce current. But only if it is set after charging has started. Otherwise the charger just said "In que - Load balancing"
> 
> The right one to use is "Dyn circuit limit". That can be set before charging has even started and will not prohibit the charger to start when a car is connected or a schedule turns it on

Hi there. Could you please share your Code of the automation? Couldnt get my Code to work..
Thanks

**Comment by olalid** [comment]
Ok, we should I guess provide some examples, but until then I can share how my setup looks.
First I have some template sensors, one set for solar charging and one for regular (typically nightly charging).
So elbil_sol_begransning_1 calculates the new limit when solar charging, and elbil_begransning_2 is just limiting the output to a value between 5 and 14A.
Likewise is elbil_natt_begransning_1 and elbil_natt_begransning_2 for regular charging.
Solar charging is single phase with target power 0W and regular charging is 3-phase charging with target power 9700W. "Target" means that the total house consumption should not be above that.

```
      elbil_sol_begransning_1:
        friendly_name: "Elbil solladdning begränsning steg 1"
        value_template: "{{ (state_attr('sensor.j21_dynamic_circuit_limit', 'state_dynamicCircuitCurrentP3') - (states('sensor.elmatare_effekt') | float/230)) | int }}"
        unit_of_measurement: "A"
        device_class: current
      elbil_sol_begransning_2:
        friendly_name: "Elbil solladdning begränsning steg 2"
        value_template: "{% if (states('sensor.elbil_sol_begransning_1') | float) < 5 %}5{% elif (states('sensor.elbil_sol_begransning_1') | float) > 14%}14{% else %}{{ states('sensor.elbil_sol_begransning_1') }}{% end\
if %}"
        unit_of_measurement: "A"
        device_class: current
      elbil_natt_begransning_1:
        friendly_name: "Elbil nattladdning begränsning steg 1"
        value_template: "{{ (state_attr('sensor.j21_dynamic_circuit_limit', 'state_dynamicCircuitCurrentP3') - (((states('sensor.elmatare_effekt') | float)-9700)/(230*3))) | int }}"
        unit_of_measurement: "A"
        device_class: current
      elbil_natt_begransning_2:
        friendly_name: "Elbil nattladdning begränsning steg 2"
        value_template: "{% if (states('sensor.elbil_natt_begransning_1') | float) < 5 %}5{% elif (states('sensor.elbil_natt_begransning_1') | float) > 14%}14{% else %}{{ states('sensor.elbil_natt_begransning_1') }}{% \
endif %}"
        unit_of_measurement: "A"
        device_class: current
```

Then I have a couple of automations that triggers the transfer of these values to the charger settings every 20 second. Which one of them runs depends on the state of input_boolean.billaddare_prioritet, which can manually changed between solar charging and regular charging, or it can be changed by some automation.
It is a bit crude but it works reasonable well.

```
- id: elbil_solel_pa
  alias: Elbil solladdning på
  trigger:
  - platform: time_pattern
    seconds: "/20"
  condition:
    condition:
    - condition: state
      entity_id: input_boolean.billaddare_prioritet
      state: "off"
  action:
  - service: easee.set_charger_circuit_dynamic_limit
    data:
      charger_id: EH189779
      currentP1: 0
      currentP2: 0
      currentP3: "{{ states('sensor.elbil_sol_begransning_2') }}"

- id: elbil_natt_pa
  alias: Elbil nattladdning på
  trigger:
  - platform: time_pattern
    seconds: "/20"
  condition:
    - condition: state
      entity_id: input_boolean.billaddare_prioritet
      state: "on"
  action:
  - service: easee.set_charger_circuit_dynamic_limit
    data:
      charger_id: EH189779
      currentP1: "{{ states('sensor.elbil_natt_begransning_2') }}"
      currentP2: "{{ states('sensor.elbil_natt_begransning_2') }}"
      currentP3: "{{ states('sensor.elbil_natt_begransning_2') }}"
```
