### ISSUE TITLE
Energy dashboard 1 hour delayed using Easee Equalizer import energy entity

### ISSUE THREAD

**Issue by gulli1986** [fondberg/easee_hass#151]
Not sure if this is related to the energy dashboard or the Equalizer integration but give it a try here first.
I found out that using the import energy entity from the Equalizer in the Energy dashboard reports hourly consumption that are exactly 1 hour delayed.

Look at the example below. The energy dashboard showed that I used 5.9 kWh during 9AM and 10AM this morning while in fact this was between 8AM and 9AM according to an hourly energy sensor that I made using the utility meter:

```
#Consumption every hour
utility_meter:
  energy:
    source: sensor.easee_equalizer_home_import_energy
    name: Hourly Energy Consumption
    cycle: hourly
```

Energy dashboard
![Untitled](https://user-images.githubusercontent.com/84970544/144397639-3598c6ad-c22a-41c8-a142-ab8757fdf720.png)

Hourly sensor showing 5.9 kWh is the last period, energy dashboard should show 5.6 kWh for the time period 9AM to 10AM, not 5.9 kWh
![2](https://user-images.githubusercontent.com/84970544/144397667-d2a20ab5-1612-4518-8c06-dfb1a27219c5.PNG)

Anyone experiencing the same issue?
