### ISSUE TITLE
Automation only has enable on/off as "action" to controll charger

### ISSUE THREAD

**Issue by large** [fondberg/easee_hass#153]
Hi!
I currently working on reducing hourly usage in my house and I want to control the Easee charger.
It is setup with a schedule to charge from 22:00 to 06:00, but if the house hourly totals is above a certain limit I want to pause to the next hour.

First version of control is like this :
```
###########################
#Stop charger
- id: '1639602865859'
  alias: 'Garasje: Stoppe lader ved for høyt forbruk'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.garasjen_status
    to: charging
  condition:
  - type: is_energy
    condition: device
    device_id: 732f06447e131fc50d2e1ecaf673117b
    entity_id: sensor.accumulated_consumption_current_hour_nustadsloyfa_4
    domain: sensor
    above: 4.5
  action:
  - type: turn_off
    device_id: 0a57fd5c74291899b431e9b10c1d0ce4
    entity_id: switch.garasjen_is_enabled
    domain: switch
  mode: restart

###########################
#Start charger again
- id: '1639603157022'
  alias: 'Garasje: Starte lader ved begynnelse på en ny time'
  description: ''
  trigger:
  - type: energy
    platform: device
    device_id: 732f06447e131fc50d2e1ecaf673117b
    entity_id: sensor.accumulated_consumption_current_hour_nustadsloyfa_4
    domain: sensor
    above: 0
    below: 4.5
  condition:
  - condition: device
    type: is_off
    device_id: 0a57fd5c74291899b431e9b10c1d0ce4
    entity_id: switch.garasjen_is_enabled
    domain: switch
  action:
  - type: turn_on
    device_id: 0a57fd5c74291899b431e9b10c1d0ce4
    entity_id: switch.garasjen_is_enabled
    domain: switch
  mode: restart
```

It seems quite "odd" to enable/disable the charger to pause/resume the charger.
When disabled the charger was greyed out in the app with an "active" button on top. Never seen that before.
Is this the correct way to control this?

Note:
I know that this charger is much "smarter" than this!
I do not need any of the load balancing and priceadjusted price-algos.
Just a simple pause/resume when connected.
