### ISSUE TITLE
Energy per hour sensor ?

### ISSUE THREAD

**Issue by ujhede** [fondberg/easee_hass#183]
### Question

I am trying to calculate the cost of a charging session using hourly rates and the energy per hour sensor from this integration.

I am having a bit of trouble figuring out what value the energy per hour sensor exposes.  It seems to be update every hour around 10 mins past the hour but the time does not seem to be consistent.  Smetimes it updates at 5 minutes past.

Is the sensor value the total charge energy since the last update or is it in the last "clock hour"  ? 

### What version of the integration are you using?

manua installation easee (opening the configuration panel give an error)

### Anything in the logs that might be useful for us?

```txt
Not that i can think of.
```

**Comment by olalid** [comment]
There is no exact timing when sensors update, this is just how the easee cloud works, it does not push out updates to all connected clients at the same time because that would use far too much bandwidth.
The value is supplied from easee cloud and we do not really know the exact algorithm behind calculating it.
But from the way it behaves I would assume that it is showing the amount of between hour marks.

PS. It would be nice to know what kind of problem you are seeing with the configuration panel?

**Comment by TheEnergy** [comment]
Im kinda hijacking this thread, but its like the same question.

I have a sensor nordpool_kwh_dk2_dkk_3_10_025, that give me this output 1.971 DKK/kWh
Is it possibel to get it to write it to the EHTEYW8B Cost per kWh sensor? so the hourly would match?

Could be nice with a script like this.

**Comment by olalid** [comment]
Yes, you can use an automation to write the current price to Easee.
I do not think that will mean that the price will be logged correctly throughout a charging session.
I think the price that is set when the charging starts is the one it will use for the whole session.
Not 100% sure though.

```
- id: update_easee_price
  alias: Easee price
  trigger:
  - platform: state
    entity_id: sensor.nordpool_kwh_dk2_dkk_3_10_025
  action:
  - service: easee.set_charging_cost
    data:
      cost_per_kwh: {{ states('sensor.nordpool_kwh_dk2_dkk_3_10_025') }}
      vat: 0
      device_id: xxxxxx
```

**Comment by TheEnergy** [comment]
Seems to be on the right track. When i run the script, this happens.

alias: Price
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.nordpool_kwh_dk2_dkk_3_10_025
condition: []
action:
  - service: easee.set_charging_cost
    data:
      cost_per_kwh:
        "[object Object]": null
      vat: 0
      device_id: cfcdc7cdf0eb5625e3341a9f62845bd1
      
     So it report back is zero to easse.

**Comment by Krabbee** [comment]
I get the same error when using sensor.
cost_per_kwh:
        "[object Object]": null
Can anyone help with that? :)

**Comment by olalid** [comment]
Can you show how your automation looks?

**Comment by Krabbee** [comment]
> Can you show how your automation looks?

Right now it looks like this: 

```
alias: "Easee Set Charging Price "
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.energi_data_service_buy
condition: []
action:
  - service: easee.set_charging_cost
    data:
      cost_per_kwh:
        - entity_id: sensor.energi_data_service_buy
      vat: 0
      device_id: 890d81a5ec62c64014c8e2beb0e231b6
      currency_id: DKK
```

And the entity looks right.
But I get this error:

![Screenshot_2023-10-23-13-56-26-59_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/fondberg/easee_hass/assets/9973968/f93bbfbc-69fc-4bd4-88e6-7dd32580bef9)

**Comment by olalid** [comment]
You can not use an entity_id: as input to cost_per_kwh.
You must provide a value, and you can do that with a template, similar to what I wrote above.
In your case it would probably be: {{ states('sensor.energi_data_service_buy') }}

**Comment by Krabbee** [comment]
> You can not use an entity_id: as input to cost_per_kwh.
> You must provide a value, and you can do that with a template, similar to what I wrote above.
> In your case it would probably be: {{ states('sensor.energi_data_service_buy') }}

I tried using the suggested template, but that does not seem to work :( 

```
service: easee.set_charging_cost
data:
  cost_per_kwh:
    '[object Object]': null
  vat: 0
  device_id: blabla...
```

Full automation:
```
alias: "Easee Set Charging Price "
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.energi_data_service_buy
condition: []
action:
  - service: easee.set_charging_cost
    data:
      cost_per_kwh:
        "[object Object]": null
      vat: 0
      device_id: 890d81a5ec62c...

```

**Comment by olalid** [comment]
This works for me:

```
- id: elbil_laddkostnad
  alias: Elbil laddkostnad
  trigger:
  - platform: state
    entity_id: sensor.elpris_total
  action:
  - service: easee.set_charging_cost
    data:
      charger_id: EHxxxxxx
      cost_per_kwh: "{{ states('sensor.elpris_total') }}"
      vat: 0
```

Your sensor has a different name of course, so your template will be different.
In your code above you have "[object Object]": null instead of a template.
If the automation editor does not allow you to create it the correct way, you need to edit the automation manually.
