### ISSUE TITLE
Get sensor für current power

### ISSUE THREAD

**Issue by Fummy1990** [fondberg/easee_hass#190]
### Feature request

I use this:
```
alias: Ladesteuerung_Auto_L1_Erhöhunv
description: ''
trigger:
  - platform: state
    entity_id: sensor.netzuerberschuss_ampere
condition:
  - condition: numeric_state
    entity_id: sensor.netzuerberschuss_ampere
    above: '0'
    below: '22'
action:
  - service: easee.set_charger_circuit_dynamic_limit
    data:
      charger_id: EH775940
      currentP1: '{{ states.sensor.easee_vorgarten_dynamic_circuit_limit.state|int + 1 }}'
      currentP2: 0
      currentP3: 0
mode: single
max: 3 
```
to charge only as much as I have overload from the pv. But I cant set only this:
```
action:
  - service: easee.set_charger_circuit_dynamic_limit
    data:
      charger_id: EH775940
      currentP1: '{{ states.sensor.easee_vorgarten_dynamic_circuit_limit.state|int + 1 }}'
mode: single
max: 3
```

to just change one phase. Is it possible to read out the currentP2 and P3 from the wallbox?

### What version of the integration are you using?

v0.9.43
