### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by Jolle1803** [fondberg/easee_hass#258]
### Question

Hello, thank you for providing this integration. 
I'm new to HA so maybe i'm doing obvious faults.

I tried to implement a button to the frontend which pause or resume charging.
It works if i only want it to either pause or start.
I tried to make it with if else so i can use one button for both actions but it just won't work.

error:
"Fehler beim Aufrufen des Diensts {% if is_state('sensor/xxx_status', 'ready_to_charge') %} easee. Service not found."

I think there's something wrong with my syntax.

```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: |
    {% if is_state('sensor.xxx_status', 'ready_to_charge') %}
      easee.pause
      data:
        charger_id: XXX
    {% if is_state('sensor.xxx_status', 'awaiting_start') %}
      easee.resume
      data:
        charger_id: XXX
    {% endif %}
entity: sensor.xxx_status
show_state: true

```

At the moment I'm just learning and having fun with HA.
I'm sure this isn't the smartest way to integrate a posibility to start and stop charging but I'm open for tips and inspiration.

Any Ideas as to what I'm doing wrong here?
Thank you :)

### What version of the integration are you using?

easee: 0.9.47 HA: 2022.12.1
