### ISSUE TITLE
variable electricity tariff

### ISSUE THREAD

**Issue by ChaotenKurt** [fondberg/easee_hass#345]
### Feature request

I have a variable electricity tariff and I would like to have this deposited with Easee via automation. Unfortunately, Easee can only store a fixed electricity price. So I could then simply hourly import the current electricity. Thank you very much.

### What version of the integration are you using?

easee version:0.9.54

**Comment by olalid** [comment]
I am not sure I understand what it is you need...?
There is already a service in this integration to set the electricity price called "set_charging_cost".
This will change the price setting in Easee cloud.
It will however not mean that Easee will log the price correctly if you change the price during a charging session.

**Comment by HolgerMiara** [comment]
This is easee (haha) to set up:
```
alias: Set Easee price / kWh
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.energi_data_service_kob {# this trigger is fired every time the price changes, replace with your electricity price entity #}
condition:
  - condition: sun
    before: sunset
    after: sunrise
    enabled: false {# disabled again because I sometimes have to fill up the car at night from the grid #}
action:
  - service: easee.set_charging_cost
    data:
      cost_per_kwh: "{{ states('sensor.energi_data_service_kob') | float(0) }}"
      vat: 0
      device_id: XXXXXXXXXXXXXXXX
      currency_id: DKK
mode: single
```
